# -*- coding: utf-8 -*-
"""BloodCell-Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JkF_Wxqr5HvLGfmB8wGzJdiii5wHYSfa

1.  Library Imports & Environment Setup
"""

import os
import time
import zipfile
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf

from google.colab import drive
from tensorflow.keras import layers, models
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

print("TensorFlow version:", tf.__version__)

drive.mount('/content/drive')

"""2. Dataset Extraction & Path Configuration"""

zip_path = "/content/drive/MyDrive/Project_datasets/bloodcell.zip"
extract_path = "/content/bloodcell"

if not os.path.exists(extract_path):
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extract_path)

print("Dataset extracted successfully.")

train_dir = None
test_dir = None

for root, dirs, files in os.walk(extract_path):
    if 'TRAIN' in dirs and train_dir is None:
        train_dir = os.path.join(root, 'TRAIN')
    if 'TEST' in dirs and test_dir is None:
        test_dir = os.path.join(root, 'TEST')

print("Train directory:", train_dir)
print("Test directory :", test_dir)

if train_dir is None or test_dir is None:
    raise ValueError("TRAIN or TEST folder not found. Check dataset structure.")

"""3. Configuration & Data Augmentation"""

img_size = (224, 224)
batch_size = 16
epochs = 10
seed = 123
AUTOTUNE = tf.data.AUTOTUNE

results = []
all_histories = {}
all_predictions = {}

data_augmentation = tf.keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.2),
    layers.RandomZoom(0.2),
])

"""4. Model Architecture Definitions"""

def build_better_cnn(num_classes):
    model = models.Sequential([
        layers.Input(shape=(224, 224, 3)),
        data_augmentation,
        layers.Rescaling(1./255),

        layers.Conv2D(32, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D(),

        layers.Conv2D(64, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D(),

        layers.Conv2D(128, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D(),

        layers.Conv2D(256, (3, 3), padding='same', activation='relu'),
        layers.BatchNormalization(),
        layers.MaxPooling2D(),

        layers.GlobalAveragePooling2D(),
        layers.Dense(224, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(num_classes, activation='softmax')
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

def build_resnet50(num_classes):
    base_model = tf.keras.applications.ResNet50(
        input_shape=(224, 224, 3),
        include_top=False,
        weights='imagenet'
    )

    # freeze first, fine-tune later half-ish
    for layer in base_model.layers[:140]:
        layer.trainable = False
    for layer in base_model.layers[140:]:
        layer.trainable = True

    preprocess_input = tf.keras.applications.resnet50.preprocess_input

    model = models.Sequential([
        layers.Input(shape=(224, 224, 3)),
        data_augmentation,
        layers.Lambda(preprocess_input),

        base_model,
        layers.GlobalAveragePooling2D(),
        layers.Dense(224, activation='relu'),
        layers.Dropout(0.3),
        layers.Dense(num_classes, activation='softmax')
    ])

    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model

def get_predictions(model, dataset):
    y_true = []
    y_pred = []

    for images, labels in dataset:
        probs = model.predict(images, verbose=0)
        preds = np.argmax(probs, axis=1)
        y_true.extend(labels.numpy())
        y_pred.extend(preds)

    return np.array(y_true), np.array(y_pred)

"""5. Data Loading & Pipeline Optimization"""

print("\n" + "="*70)
print(f"RUNNING EXPERIMENTS FOR BATCH SIZE = {batch_size}")
print("="*70)

# Load datasets
train_ds = tf.keras.preprocessing.image_dataset_from_directory(
    train_dir,
    validation_split=0.2,
    subset="training",
    seed=seed,
    image_size=img_size,
    batch_size=batch_size
)

val_ds = tf.keras.preprocessing.image_dataset_from_directory(
    train_dir,
    validation_split=0.2,
    subset="validation",
    seed=seed,
    image_size=img_size,
    batch_size=batch_size
)

test_ds = tf.keras.preprocessing.image_dataset_from_directory(
    test_dir,
    image_size=img_size,
    batch_size=batch_size,
    shuffle=False
)

class_names = train_ds.class_names
num_classes = len(class_names)

print("Class names:", class_names)

# Optimize pipeline
train_ds = train_ds.shuffle(1000, seed=seed).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.prefetch(buffer_size=AUTOTUNE)
test_ds = test_ds.prefetch(buffer_size=AUTOTUNE)

callbacks = [
    tf.keras.callbacks.EarlyStopping(
        monitor='val_loss',
        patience=3,
        restore_best_weights=True
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        monitor='val_loss',
        factor=0.5,
        patience=2,
        verbose=1
    )
]

# --------------------------------------------
# TRAIN BETTER CNN
# --------------------------------------------
print(f"\n--- Training Better CNN | Batch Size = {batch_size} ---")
cnn_model = build_better_cnn(num_classes)

start_time = time.time()
history_cnn = cnn_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=epochs,
    callbacks=callbacks,
    verbose=1
)
cnn_training_time = time.time() - start_time

cnn_test_loss, cnn_test_acc = cnn_model.evaluate(test_ds, verbose=0)
y_true_cnn, y_pred_cnn = get_predictions(cnn_model, test_ds)

all_histories[("CNN", batch_size)] = history_cnn.history
all_predictions[("CNN", batch_size)] = (y_true_cnn, y_pred_cnn)

results.append({
    "model": "CNN",
    "batch_size": batch_size,
    "train_accuracy": max(history_cnn.history["accuracy"]) * 100,
    "val_accuracy": max(history_cnn.history["val_accuracy"]) * 100,
    "test_accuracy": cnn_test_acc * 100,
    "training_time_sec": cnn_training_time,
    "epochs_run": len(history_cnn.history["loss"])
})

print(f"\nClassification Report: CNN | Batch Size = {batch_size}")
print(classification_report(y_true_cnn, y_pred_cnn, target_names=class_names))

# --------------------------------------------
# TRAIN RESNET50
# --------------------------------------------
print(f"\n--- Training ResNet50 | Batch Size = {batch_size} ---")
resnet_model = build_resnet50(num_classes)

start_time = time.time()
history_resnet = resnet_model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=epochs,
    callbacks=callbacks,
    verbose=1
)
resnet_training_time = time.time() - start_time

resnet_test_loss, resnet_test_acc = resnet_model.evaluate(test_ds, verbose=0)
y_true_resnet, y_pred_resnet = get_predictions(resnet_model, test_ds)

all_histories[("ResNet50", batch_size)] = history_resnet.history
all_predictions[("ResNet50", batch_size)] = (y_true_resnet, y_pred_resnet)

results.append({
    "model": "ResNet50",
    "batch_size": batch_size,
    "train_accuracy": max(history_resnet.history["accuracy"]) * 100,
    "val_accuracy": max(history_resnet.history["val_accuracy"]) * 100,
    "test_accuracy": resnet_test_acc * 100,
    "training_time_sec": resnet_training_time,
    "epochs_run": len(history_resnet.history["loss"])
})

print(f"\nClassification Report: ResNet50 | Batch Size = {batch_size}")
print(classification_report(y_true_resnet, y_pred_resnet, target_names=class_names))

